# Generated by Django 3.1.3 on 2021-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200831_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='content',
        ),
        migrations.AddField(
            model_name='avatar',
            name='resource',
            field=models.CharField(default='sm.ms/image/y7brI2GnKfCvJXl', max_length=100),
        ),
    ]
